### ISSUE TITLE
Setup smoke test Github action

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#108]

**Comment by keithkennedyHO** [comment]
Run on schedule - midnight
Run just before deployment to main - stop main update if test fail

- check key pages are served
- could check css / js are served?

**Comment by edhamiltonHO** [comment]
Dropping priority in light of view to use different hosting for the site

**Comment by edhamiltonHO** [comment]
Closing this in light of migration from github pages
