### ISSUE TITLE
Change phase banner status from 'Alpha'

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#265]
**What is the feature or enhancement you are suggesting?**
The current phase banner states the site is in 'Alpha', i.e. it is a prototype. This phase banner tag should be changed to a new value, suggest one of the below, or similar:

`Beta`
`New service`
`Seeking feedback`

**What would be the benefit of doing this?**
Once the site has moved to new hosting, is available at engineering.homeoffice.gov.uk and has completed accessibility audit, then the site will definitively not be a prototype and should not be marked as 'Alpha'. Updating the phase banner to reflect this will accurately mark the status of the site and content.

**Additional information**
We probably want to avoid giving the impression that the site has been through a service assessment, as it hasn't (though has been developed to that standard for the most part)

**Please confirm the below**

- [x] I have checked through the issues on the repository and this has not already been suggested

**Comment by keithkennedyHO** [comment]
Should we also consider changing the link to no longer open in a new tab given that the feedback page is now within the site itself?

**Comment by edhamiltonHO** [comment]
Have contacted the Assurance team to see if there is guidance we should be following

**Comment by edhamiltonHO** [comment]
Agreed to change to 'New service'
