### ISSUE TITLE
Review technical documentation files

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#274]
**Which content do you think should be reviewed?**
Documentation files in repo root, e.g. README.md, CONTRIBUTING.md, and the technical decision log

**Why do you think we should review this?**
As part of the migration to `UKHomeOffice` and new hosting, a number of our files will need to be amended. Also the technical decision log will need to reflect the chance

**Please confirm the below**

- [x] I have checked through the issues on the repository and don't think this has already been suggested

**Comment by edhamiltonHO** [comment]
- [ ] Update deployment documentation

**Comment by keithkennedyHO** [comment]
>  Make changes - do we want this to recommend forking the repo?

I am not aware of us requiring this as other repositories do so unsure here. This is not how PRs generated by guilds or development teams are working (which is fine, of course). However, for external contributors, this is a good approach to take, I think and worth suggesting.

**Comment by edhamiltonHO** [comment]
OK, I think leave this as is, it is not broken

Looking through though I noticed that section on raising a security vulnerability issue was out of sequence and interfering with the flow for making a change. I've added little commit to fix
