### ISSUE TITLE
Set up redirects from old repo and site to new repo and site

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#285]
- [x] Recreate original repo in HO-CTO
- [x] Setup GitHub pages on that repo, that redirects to engineering.homeoffice.gov.uk
- [x] Create readme in repo that points visitors to repo to go to new repo
- [x] Configure repo for branch protection and correct management/admin access

**Comment by edhamiltonHO** [comment]
Could be option to archive original repo and include redirect in archive message

**Comment by jeff-horton-ho-sas** [comment]
https://github.com/HO-CTO/engineering-guidance-and-standards/pull/1

**Comment by edhamiltonHO** [comment]
Complete and tested
