### ISSUE TITLE
Not clear how to propose a change/update for a standard[BUG]

### ISSUE THREAD

**Issue by GraemeSutherlandHO** [UKHomeOffice/engineering-guidance-and-standards#313]
**Describe the bug**
I want to propose a change to a standard. Going to the github Issues page, it isn't clear which option to choose.

**To Reproduce**
1.Go to github issues page
2. try to work out where to raise a change to a standard

**Expected behavior**
There should be a clear, unambiguous choice to suggest a change to a standard, principle or pattern

**Screenshots**

**Desktop (please complete the following information):**
POISE laptop

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by edhamiltonHO** [comment]
Original intent was for the 'Propose review of content' Github Issue template to cover this use case (https://github.com/UKHomeOffice/engineering-guidance-and-standards/issues/new?assignees=&labels=&projects=&template=review-content.md&title=)

Description and name for that issue template could be amended to address this bug. e.g.
`Propose a review/change of standards, patterns, principles or other site content

Worth also considering adding a clear link to a standards page on the site (e.g. 'suggest a change to this standard/pattern/principle') that links to the same issue template
