### ISSUE TITLE
SEGAS-00003 should explicitly require naming SRO

### ISSUE THREAD

**Issue by GraemeSutherlandHO** [UKHomeOffice/engineering-guidance-and-standards#314]
We welcome feedback on all of the content on the site. Please let us know what you think we could change or improve below

**Which content do you think should be reviewed?**
SEGAS-00003
https://engineering.homeoffice.gov.uk/standards/minimal-documentation-set-for-a-product/

**Why do you think we should review this?**
In minimal documentation, is useful to mention who is the senior responsible owner (SRO) for a product. 

**Do you have a suggestion for how this could be improved?**
In minimal documentation, is useful to mention who is the senior responsible owner (SRO) for a product. This could be recommended or required. 

**Additional information**

**Please confirm the below**

- [x ] I have checked through the issues on the repository and don't think this has already been suggested

**Comment by robertdeniszczyc2** [comment]
Would SRO be included under "key stakeholders" which is already called out, or should SRO have its own line item?

**Comment by edhamiltonHO** [comment]
I had the same thought, and wondered if there where any other specific, and common, stakeholders we might want to specify?

I think if we have multiple along lines of the above then a nested list under key stakeholders would be a good. If not, then an additional line, or incorporation into the existing line - e.g. 'including the Senior Responsible Owner (SRO)', even if that is a little clunky

**Comment by GraemeSutherlandHO** [comment]
SRO is a bit more important than a stakeholder.  I'd list SRO separately.

Useful reference: https://www.gov.uk/government/publications/the-role-of-the-senior-responsible-owner/the-role-of-the-senior-responsible-owner

**Comment by robertdeniszczyc2** [comment]
> SRO is a bit more important than a stakeholder. I'd list SRO separately.
> 
> Useful reference: https://www.gov.uk/government/publications/the-role-of-the-senior-responsible-owner/the-role-of-the-senior-responsible-owner

That's a useful link, we can link to that
