### ISSUE TITLE
Update dependabot config for LTS version bumps only

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#324]

**Comment by jeff-horton-ho-sas** [comment]
https://github.com/dependabot/dependabot-core/issues/2247#issuecomment-831513592

**Comment by jeff-horton-ho-sas** [comment]
Fixed by @LiamMacP - see this comment on node 21 alpine dependabot PR https://github.com/UKHomeOffice/engineering-guidance-and-standards/pull/317#issuecomment-1785056193
