### ISSUE TITLE
[BUG] Redirects from old Github Pages site only work for the index page

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#341]
**Describe the bug**
Redirects from old Github Pages site only work for the index page

**To Reproduce**
1. Go to [here](https://ho-cto.github.io/engineering-guidance-and-standards/principles/end-to-end-product-ownership/).'

2. See error

**Expected behavior**
Would redirect through to new page on engineering.homeoffice.gov.uk

**Comment by jeff-horton-ho-sas** [comment]
https://github.com/HO-CTO/engineering-guidance-and-standards/pull/3

**Comment by jeff-horton-ho-sas** [comment]
Redirects have been added to the previous repository for all pages.
Example url now redirects correctly.
