### ISSUE TITLE
[Review content] - Update About page to include information on guilds and previous usage of term 'SEGAS'

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#342]
**Which content do you think should be reviewed?**
About page

**Why do you think we should review this?**
Could give more information to people viewing site for the first time

**Do you have a suggestion for how this could be improved?**
Brief explanations of SEGAS (as acronym) and guilds

**Please confirm the below**

- [x] I have checked through the issues on the repository and don't think this has already been suggested

**Comment by robertdeniszczyc2** [comment]
We can probably use some of the information from the [CONTRIBUTING doc](https://github.com/UKHomeOffice/engineering-guidance-and-standards/blob/main/CONTRIBUTING.md#organisation-of-content) for this
