### ISSUE TITLE
Disambiguate L2 docs from SDP?

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/engineering-guidance-and-standards#364]
**Which content do you think should be reviewed?**
SEGAS-00003: https://engineering.homeoffice.gov.uk/standards/minimal-documentation-set-for-a-product/

> ## Product documentation MUST include incident management information
> 
> An incident management process should include technical points of contact, runbooks, and disaster recovery information.

**Why do you think we should review this?**
I think this is a little confusing, as it appears to be a mixture of things that would be covered in the SDP, and also L2 information.

**Do you have a suggestion for how this could be improved?**
I'm not sure, I just think it needs some thought.

My gut instinct is to make it about runbooks for anticipated, non-automateable tasks. (And specifically call out disaster recovery.)

I think the SDP is covered elsewhere.

**Please confirm the below**

- [x] I have checked through the issues on the repository and don't think this has already been suggested

**Comment by robertdeniszczyc2** [comment]
Hi,

Could I confirm what SDP stands for in this context please?

Thankyou

**Comment by daniel-ac-martin** [comment]
Service Design Pack, if I remember correctly. It's what they put together when you on-board to Enterprise/Live services (L1).
