### ISSUE TITLE
Consider Markdown linting as an automated step in the pipeline

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#40]

**Comment by edhamiltonHO** [comment]
Need decisions on:

- [ ] Whether we override the xgov plugin breaks=true flag
- [ ] Whether to include inclusive language plugin
- [ ] What linting rules we want to include/ignore from standard md set
- [ ] If we want to add any other custom linting rules

**Comment by jeff-horton-ho-sas** [comment]
Closing stale PR for this. When this is revisted - code changes were adding `markdownlint-cli` as a dependency, and setting up an npm script to run it (`markdownlint docs/**/*.md`).

**Comment by edhamiltonHO** [comment]
Closing as, following review, there is not enough value in md linting. Ally tests cover assurance of creating good HTML.
