### ISSUE TITLE
Consider use and construction of content IDs for standards and other content

### ISSUE THREAD

**Issue by edhamiltonHO** [UKHomeOffice/engineering-guidance-and-standards#71]
Standards currently have unique IDs of construction SEGAS-xxxxx

We want all content to have permanent and unique IDs
We may want to use a different prefix (as SEGAS is not publicly understood)
We may want to use different prefixes for different types of content

Whichever construction and usage is selected, we will want some mechanism to allow users to know which content ID they should use for their new content so that they are permanent and unique.

**Comment by edhamiltonHO** [comment]
Also need to ensure that content IDs are correctly displayed on content pages

**Comment by keithkennedyHO** [comment]
We may wish to consider a unit test that verifies no duplicate ID has been used across documents.

**Comment by edhamiltonHO** [comment]
Closing issue as not needed. Standard content IDs are working as is and other content doesn't require them. Issue is vague so any future issues can be raised to directly meet a use case
